FROM node:22-alpine

RUN apk add --no-cache bash git && corepack enable

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN --mount=type=cache,target=/home/node/.pnpm-store \
    pnpm install --frozen-lockfile

EXPOSE 1337

CMD ["pnpm", "develop"]